#!/usr/bin/env bash
#
# Install Nginx (if not already installed)
apt-get update
apt-get install -y nginx

# Configure Nginx redirection
echo "
server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}
" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
service nginx restart
