#!/usr/bin/env bash
# Install Nginx (if not already installed)
apt-get update
apt-get install -y nginx

# Configure Nginx custom 404 page
echo "
server {
    listen 80;
    server_name _;

    location / {
        root /var/www/html;
        index index.html index.htm;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
        root /var/www/html;
        echo 'Ceci n'est pas une page';
    }
}
" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restart Nginx
service nginx restart
