#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

# Update package lists
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Create a custom HTML page for 404 error
sudo tee /var/www/html/404.html > /dev/null <<EOT
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>
EOT

# Configure Nginx to use the custom 404 page
sudo sed -i 's|server_name _;|server_name _;\n\n    error_page 404 /404.html;\n    location = /404.html {\n        root /var/www/html;\n        internal;\n    }|' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

