#!/usr/bin/env bash
# This script configures a new Ubuntu machine to add a custom HAProxy response header

# Update package information and install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# Create a custom HAProxy configuration file
echo 'http-response set-header X-Served-By %[hostname]' | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

# Restart HAProxy to apply the changes
sudo service haproxy restart
