#!/usr/bin/env bash
# installing a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
frontend sage-frontend
        bind *:80
        mode http
        default_backend sage-backend

backend sage-backend
        balance roundrobin
        server 117206-web-01 100.25.48.64:80 check
        server 117206-web-02 52.87.232.106:80 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
