#!/usr/bin/env bash
#this script echos "Best school" 10 times on the screen
# Display Best School 10 times, with Hi on the ninth

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
